#!/usr/bin/env python3
"""Build a Synthesia video from a scene table. SCENES is the source of truth; the demo scenes below are the
reference film (every clip shows one lesson). Replace them with your own.

  python3 tools/build.py words     # word count and runtime estimate per clip
  python3 tools/build.py script    # the clean text per clip, no SSML, one paragraph per line: the recording sheet
  python3 tools/build.py export    # pages -> out/<id>.png (image) or out/<id>.mp4 (video, on its beats)
  python3 tools/build.py upload    # out/* -> Synthesia assets; ids cached in out/assets.json by content hash
  python3 tools/build.py request   # -> out/request.json, all clips in order
  python3 tools/build.py all       # the three above; never renders
  python3 tools/build.py render    # submits out/request.json as a TEST render (watermarked, free), waits, downloads out/film.mp4
  python3 tools/build.py render --final   # spends video minutes; only when the user explicitly asks
  python3 tools/build.py mux       # each clip's picture + its voice (audio=) -> out/scenes/<id>.mp4, exact sync, no watermark
  python3 tools/build.py assemble  # out/film.mp4 cut at out/cuts.json, muxed scenes spliced in -> out/assembled.mp4

Voice sync (see tools/sync.py): render, `sync.py cuts`, `sync.py voice`, `sync.py beats`, then `export`, `mux`, `assemble`.

Speakers are the CAST table below; pronunciations are SUBS. Both are merged with a house file if there is one
(see load_house). Personal avatars of some types (EXPRESS-2) are refused by the API: render with a stock avatar
and swap it in Studio if the render is shown.
"""
import hashlib, json, os, re, shutil, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "out")
SYN = os.path.join(ROOT, "tools", "synthesia.py")
EXPORT = os.path.join(ROOT, "tools", "export-frames.mjs")
FPS = 30
T0, HOLD = 4.0, 3.0                                  # stage.js: capture start in page time, hold after the last beat


# ---- house file ---------------------------------------------------------------------------------------
# A person's or company's standing choices, kept outside the plugin and outside any one film: pronunciations,
# the default cast, and house rules for whoever writes the scripts. The first that exists wins:
#   $SYNTHESIA_HOUSE, ./house.json (this project), ~/.claude/synthesia-house.json
# Shape (see examples/ in the plugin repo):
#   {"subs": [["term", "alias"], ["term", "alias", "ipa"]],
#    "cast": {"host": {"avatar": "<id>", "voice": "<id>"}, ...},
#    "rules": ["free text, read by Claude, ignored by the build"]}
def load_house():
    for p in (os.environ.get("SYNTHESIA_HOUSE"), os.path.join(ROOT, "house.json"),
              os.path.expanduser("~/.claude/synthesia-house.json")):
        if p and os.path.exists(p):
            return json.load(open(p)), p
    return {}, None


HOUSE, HOUSE_PATH = load_house()

# The cast: who can speak in this film. A clip names its speaker with who= (default "host"). The API puts exactly
# one avatar in a clip, so a hand-off between presenters is a cut between two clips; two avatars in one frame is
# Studio-only. Keep each voice with its avatar: a voice is not tied to a face, so mismatches are easy to make.
# Order of precedence: these stock defaults < the house file's cast < env SYNTHESIA_AVATAR / SYNTHESIA_VOICE (host).
CAST = {
    "host": dict(avatar="c43d0b11-61e9-483c-a0f7-26a7bfcb6510",       # Carly (stock, version 3)
                 voice="13173f72-713d-49b9-a511-2b1f575a5a5d"),       # Zola - Neutral, en-US (Studio: Noa)
    "expert": dict(avatar="894c9b8a-e3a7-40b7-b7e6-7441faceb46e",     # Jaz (stock, EXPRESS-1)
                   voice="0f023a7e-c569-4c50-ac93-6f365ac722ee"),     # Jaz - Breezy, en-US
}
CAST.update({k: dict(CAST.get(k, {}), **v) for k, v in HOUSE.get("cast", {}).items()})
CAST["host"] = dict(CAST["host"], **{k: os.environ[e] for k, e in (("avatar", "SYNTHESIA_AVATAR"), ("voice", "SYNTHESIA_VOICE")) if e in os.environ})
BLACK = "black.png"                                  # solid background for presenter clips, generated by `export`
TITLE = "Synthesia reference build"
CALLBACK = "synthesia-reference"

# ---- pronunciation ------------------------------------------------------------------------------------
# Applied to every script by ssml(); whole-word, longest term first. (term, alias[, ipa]). This film's own terms;
# the house file's are added, and a term listed here wins over the house's. Keep in step with SCENEPLAN.md
# section 2. Scripts stay plain prose.
SUBS = [
    ("PostgreSQL", "Postgres Q L"),
    ("kubectl", "cube control"),
    ("nginx", "engine X", "ˈɛndʒɪn ɛks"),
    ("SQL", "sequel"),
]
_mine = {t[0] for t in SUBS}
SUBS = sorted(SUBS + [tuple(t) for t in HOUSE.get("subs", []) if t[0] not in _mine], key=lambda t: -len(t[0]))


def ssml(text):
    for term, alias, *ipa in SUBS:
        pat = r"(?<![\w-])" + re.escape(term) + r"(?![\w-])"
        extra = f' ipaAlias="{ipa[0]}"' if ipa else ""
        text = re.sub(pat, f'<sub alias="{alias}"{extra}>{term}</sub>', text)
    return text


# One beat boundary in an animated script. 1.5 s, not less: sentence pauses reach 1.0 s in long narration and
# a 0.8 s break could not be told apart from them. Every BEAT is one step of the page's beats() list.
BEAT = ' <break time="1.5s"/> '
BEAT_S = 1.5

# ---- scene table --------------------------------------------------------------------------------------
# One entry per clip, in running order. kinds:
#   video : an HTML animation (stage.js page, timed by beats) or an existing .mp4 used as is
#   image : a static HTML card (one frame exported at start, default 4 s) or an existing .png/.jpg
#   cam   : the speaker full frame on BLACK; align= "left" | "center" (default) | "right"
# who= picks the speaker from CAST (default "host"). inset= on an image/video clip shows the speaker standing over
# the picture, scaled down and anchored at a bottom corner, instead of voice only: inset=dict(align="right", scale=0.6).
# Leave that corner empty on the page. (Not "circular": a circle is fixed to the centre of the frame, the API rejects
# horizontalAlign with it, and scale 1.0 fills the full height; it only suits a round cut-out over a screen recording.)
# file may carry a ?query for the page. script is plain prose in short paragraphs ("\n\n"): the voice takes a
# new onset at each, and modulates on "..." and "!". Put a "." before a leading <break>, else the picture starts
# late by the same amount. A script that is only a <break> renders ~1.5 s longer than asked.
# audio= is the clip's frozen voice (cut from a render by sync.py, or a real person's recording); `mux` joins it.
SCENES = [
    # Lesson: the presenter clip, a stock avatar on an uploaded black PNG; the "." before a leading break.
    dict(id="r1", kind="cam", script=(
        '. <break time="0.5s"/> This is the reference build for Synthesia films. '
        "Every clip in it shows one lesson, and says which.\n\n"
        "This one is the presenter. A stock avatar, full frame, on a black picture we upload ourselves. "
        "Your own avatar can be swapped in later, in Studio.")),
    # Lesson: pronunciation lives in one table (SUBS, plus the house file); paragraphs and "..." shape the read.
    dict(id="r2", kind="image", file="r2.html", script=(
        "Some words the voice gets wrong. So they are fixed once, in a table.\n\n"
        "nginx. kubectl. SQL. PostgreSQL.\n\n"
        "The build wraps each of them in a sub tag... and the scripts stay plain prose.")),
    # Lesson: an animation that follows the voice. One BEAT per step; the times are measured, never trusted.
    dict(id="r3", kind="video", file="r3.html", audio="out/voice/r3.mp3", script=(
        "The film is a build. A scene table in Python holds every clip, and every word."
        + BEAT + "Export turns each page into pictures, frame by frame, on a virtual clock."
        + BEAT + "Upload sends only the files that changed."
        + BEAT + "And render asks for a test video. Free, and watermarked.")),
    # Lesson: a still drawn with the animation stylesheet (no beats), and why the voice is frozen.
    dict(id="r4", kind="image", file="r4.html", script=(
        "The voice is never read the same way twice. The same script, rendered again, moves by seconds.\n\n"
        "So the animation never trusts a render. We cut the voice out of one take, measure its pauses, "
        "export the picture on them, and join the two ourselves.\n\n"
        "That is how the last clip stayed in step.")),
    # Lesson: a second presenter. The host hands off on a cut, standing to one side so the hand-off reads as a turn.
    dict(id="r5", kind="cam", align="left", script=(
        "That is the build. A film can have more than one presenter, too...\n\n"
        "For the technical part, over to our expert.")),
    # Lesson: the expert (who="expert") speaks over a picture, scaled down in its corner, so the picture stays readable.
    dict(id="r6", kind="image", file="r6.html", who="expert", inset=dict(align="right", scale=0.6), script=(
        "Thanks, Carly. The API puts exactly one avatar in each clip. So a hand-off is a cut, "
        "and every clip names who speaks, from a cast table in the build.\n\n"
        "Over a picture, I stand in the corner, scaled down... and the picture stays readable.\n\n"
        "What the API cannot do is put the two of us in one frame. That is a job for Studio.")),
    # Lesson: a silent end card, last, so it can be cut off. A lone 5 s break renders ~6.5 s.
    dict(id="r7", kind="image", file="r7.html", script='<break time="5s"/>'),
]


def run(cmd, **kw):
    return subprocess.run(cmd, check=True, text=True, capture_output=True, cwd=ROOT, **kw).stdout.strip()


def duration(f):
    return float(run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", f]))


def is_html(sc):
    return sc.get("file", "").split("?")[0].lower().endswith(".html")   # file may carry ?query


def asset_file(sc):
    if sc["kind"] == "cam":
        return None
    f = sc.get("file", "")
    if f.lower().endswith((".mp4", ".webm", ".png", ".jpg", ".jpeg")):
        return os.path.join(ROOT, f)                       # used as is
    return os.path.join(OUT, sc["id"] + (".png" if sc["kind"] == "image" else ".mp4"))


def voice_file(sc):
    a = sc.get("audio")
    return os.path.join(ROOT, a) if a and os.path.exists(os.path.join(ROOT, a)) else None


def beat_times(sc):
    """Seconds into the clip at which each beat starts. Measured times (out/beats.json, from sync.py beats)
    win; otherwise an estimate: the voice starts ~0.8 s into the clip, 2.8 words/s, plus the BEAT itself.
    The estimate drifts (5.5 s late by the last beat on a one-minute scene), which is why it gets measured."""
    path = os.path.join(OUT, "beats.json")
    if os.path.exists(path):
        measured = json.load(open(path)).get(sc["id"])
        if measured:
            return measured, "measured"
    t, out = 0.8, []
    for seg in sc["script"].split(BEAT):
        out.append(round(t, 2))
        t += len(plain(seg).split()) / 2.8 + BEAT_S + breaks(seg)
    return out, "estimate"


def export():
    os.makedirs(OUT, exist_ok=True)
    run(["ffmpeg", "-loglevel", "error", "-y", "-f", "lavfi", "-i", "color=black:s=1920x1080", "-frames:v", "1", os.path.join(OUT, BLACK)])
    for sc in SCENES:
        if sc["kind"] == "cam" or not is_html(sc):
            continue
        frames = os.path.join(OUT, "frames-" + sc["id"])
        shutil.rmtree(frames, ignore_errors=True)          # stale frames from a longer export would be encoded too
        if sc["kind"] == "image":
            run(["node", EXPORT, sc["file"], frames, "1", str(sc.get("start", T0)), str(sc.get("start", T0) + 1)])
            os.replace(os.path.join(frames, "00000.png"), asset_file(sc))
            shutil.rmtree(frames, ignore_errors=True)
            print(sc["id"], "->", os.path.basename(asset_file(sc)))
            continue
        page, end = sc["file"], sc.get("end")
        if BEAT in sc["script"]:                           # a stage.js page timed by beats
            b, src = beat_times(sc)
            page += ("&" if "?" in page else "?") + "beats=" + ",".join(str(x) for x in b)
            clip = b[-1] + HOLD
            if voice_file(sc):                             # never shorter than the frozen voice it will be muxed with
                clip = max(clip, duration(voice_file(sc)))
            end = T0 + clip
            print(sc["id"], "beats", b, f"({src})")
        args = ["node", EXPORT, page, frames, str(FPS), str(sc.get("start", T0))] + ([str(end)] if end else [])
        print(run(args))
        mp4 = asset_file(sc)
        run(["ffmpeg", "-loglevel", "error", "-y", "-framerate", str(FPS), "-i", os.path.join(frames, "%05d.png"),
             "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18", "-movflags", "+faststart", mp4])
        shutil.rmtree(frames, ignore_errors=True)
        print(sc["id"], "->", os.path.basename(mp4), f"{duration(mp4):.1f}s")


def upload():
    cache_path = os.path.join(OUT, "assets.json")
    cache = json.load(open(cache_path)) if os.path.exists(cache_path) else {}
    files = [os.path.join(OUT, BLACK)] + [f for f in (asset_file(sc) for sc in SCENES) if f]
    seen = set()
    for f in files:
        key = os.path.relpath(f, ROOT)
        if key in seen:                                    # two clips may share one picture (a hold)
            continue
        seen.add(key)
        h = hashlib.sha256(open(f, "rb").read()).hexdigest()
        if cache.get(key, {}).get("sha256") == h:
            print("cached  ", key, cache[key]["id"])
            continue
        aid = run(["python3", SYN, "upload", f])
        cache[key] = {"sha256": h, "id": aid}
        print("uploaded", key, aid)
        json.dump(cache, open(cache_path, "w"), indent=1)


def request():
    cache = json.load(open(os.path.join(OUT, "assets.json")))
    clips = []
    for sc in SCENES:
        who = CAST[sc.get("who", "host")]
        clip = {"avatar": who["avatar"], "scriptText": ssml(sc["script"]), "transition": "none"}   # no scriptLanguage with scriptText
        if sc["kind"] == "cam":
            clip["avatarSettings"] = {"style": "rectangular", "voice": who["voice"], "horizontalAlign": sc.get("align", "center"), "scale": 1.0}
            clip["background"] = cache[os.path.relpath(os.path.join(OUT, BLACK), ROOT)]["id"]
        else:
            if "inset" in sc:                              # the speaker over the picture, scaled from a bottom corner
                clip["avatarSettings"] = {"style": "rectangular", "voice": who["voice"], "horizontalAlign": sc["inset"].get("align", "right"),
                                          "scale": sc["inset"].get("scale", 0.6)}
            else:
                clip["avatarSettings"] = {"style": "voiceOnly", "voice": who["voice"]}
            clip["background"] = cache[os.path.relpath(asset_file(sc), ROOT)]["id"]
            if sc["kind"] == "video":                      # clip lasts as long as the longer of voice and picture
                clip["backgroundSettings"] = {"videoSettings": {"shortBackgroundContentMatchMode": "freeze",
                                                                 "longBackgroundContentMatchMode": "extend_content"}}
        clips.append(clip)
    req = {"test": True, "title": TITLE, "visibility": "private", "aspectRatio": "16:9", "callbackId": CALLBACK, "input": clips}
    path = os.path.join(OUT, "request.json")
    json.dump(req, open(path, "w"), indent=1, ensure_ascii=False)
    print("wrote", os.path.relpath(path, ROOT), f"({len(clips)} clips)")


def next_take():
    """Takes are numbered across renders (out/take.txt) and stamped into the title, because Studio's own list
    shows every video as "1 hour ago" after a short while and titles are the only way to tell takes apart."""
    path = os.path.join(OUT, "take.txt")
    n = int(open(path).read().strip() or 0) + 1 if os.path.exists(path) else 1
    open(path, "w").write(str(n))
    return n


def render(final=False):
    import time
    req = json.load(open(os.path.join(OUT, "request.json")))
    req["test"] = not final
    take = next_take()
    tag = f"take {take} · {time.strftime('%Y-%m-%d %H:%M')}" + (" · FINAL" if final else "")
    req["title"] = f"{TITLE} · {tag}"
    req["callbackId"] = f"{CALLBACK} · {tag}"
    print("title:", req["title"])
    tmp = os.path.join(OUT, "request.submit.json")
    json.dump(req, open(tmp, "w"), ensure_ascii=False)
    vid = run(["python3", SYN, "create", tmp])
    print("video", vid, "(FINAL, spends minutes)" if final else "(test)")
    open(os.path.join(OUT, "video.txt"), "w").write(vid)   # for the render log and later version downloads
    film = os.path.join(OUT, "film.mp4")
    subprocess.run(["python3", SYN, "wait", vid, film], check=True, cwd=ROOT)
    shutil.copy(film, os.path.join(OUT, f"film-take{take}.mp4"))   # later Studio edits change what the id downloads


def mux():
    """Each clip's picture with its voice (audio=): out/scenes/<id>.mp4, exact sync, no watermark. A still is
    held for the voice plus a one-second tail; an animation (exported on beats measured from that same voice
    file, and at least as long) is cut to the voice. Presenter clips are camera files, not muxed."""
    d = os.path.join(OUT, "scenes")
    os.makedirs(d, exist_ok=True)
    for sc in SCENES:
        if not sc.get("audio") or sc["kind"] == "cam":
            continue
        a = voice_file(sc)
        if not a:
            print(sc["id"], "no voice yet:", sc["audio"]); continue
        pic, out = asset_file(sc), os.path.join(d, sc["id"] + ".mp4")
        if pic.lower().endswith((".png", ".jpg", ".jpeg")):
            run(["ffmpeg", "-loglevel", "error", "-y", "-loop", "1", "-framerate", str(FPS), "-i", pic, "-i", a,
                 "-af", "apad=pad_dur=1", "-shortest", "-c:v", "libx264", "-tune", "stillimage", "-pix_fmt", "yuv420p",
                 "-c:a", "aac", "-b:a", "192k", "-movflags", "+faststart", out])
        else:
            run(["ffmpeg", "-loglevel", "error", "-y", "-i", pic, "-i", a, "-map", "0:v", "-map", "1:a", "-t", f"{duration(a):.3f}",
                 "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "18", "-c:a", "aac", "-b:a", "192k", "-movflags", "+faststart", out])
        print(sc["id"], "->", os.path.relpath(out, ROOT), f"{duration(out):.1f}s")


def assemble():
    """What the editor would do, for a check or a reference: the render cut at its clip boundaries
    (out/cuts.json from sync.py cuts), every clip that has a muxed scene replaced by it, joined again."""
    cuts = json.load(open(os.path.join(OUT, "cuts.json")))
    film, bounds = os.path.join(ROOT, cuts["film"]), cuts["cuts"] + [cuts["duration"]]
    ins, parts = [], []
    for k, sc in enumerate(SCENES):
        scene = os.path.join(OUT, "scenes", sc["id"] + ".mp4")
        if os.path.exists(scene):
            ins += ["-i", scene]; src = "spliced"
        else:
            ins += ["-ss", f"{bounds[k]:.3f}", "-to", f"{bounds[k + 1]:.3f}", "-i", film]; src = "render"
        parts.append(f"[{k}:v]scale=1920:1080,fps={FPS},format=yuv420p,setpts=PTS-STARTPTS[v{k}];"
                     f"[{k}:a]aresample=48000,aformat=channel_layouts=stereo,asetpts=PTS-STARTPTS[a{k}];")
        print(f"{sc['id']:6s} {src}")
    n = len(SCENES)
    graph = "".join(parts) + "".join(f"[v{k}][a{k}]" for k in range(n)) + f"concat=n={n}:v=1:a=1[v][a]"
    out = os.path.join(OUT, "assembled.mp4")
    run(["ffmpeg", "-loglevel", "error", "-y"] + ins + ["-filter_complex", graph, "-map", "[v]", "-map", "[a]",
         "-c:v", "libx264", "-crf", "20", "-c:a", "aac", "-b:a", "192k", "-movflags", "+faststart", out])
    print("wrote", os.path.relpath(out, ROOT), f"{duration(out):.1f}s")


def plain(text):
    return re.sub(r"^\.\s+", "", re.sub(r"[ \t]+", " ", re.sub(r"<[^>]+>", " ", text)).strip())   # the "." before a leading break is not a word


def breaks(text):
    return sum(float(x) for x in re.findall(r'<break time="([\d.]+)s"/>', text))


def words(wps=2.8, boundary=2.2):
    """Estimate only: stock voices measured 2.8 words/s on long narration and 3.4 on short card scripts,
    boundaries 1.9-2.2 s. Measure the first test render and correct these."""
    total = 0
    for sc in SCENES:
        n = len(plain(sc["script"]).split())
        total += n
        print(f"{sc['id']:8s} {n:4d} words  ~{n/wps + breaks(sc['script']):5.0f} s speech  (+{breaks(sc['script']):.1f} s breaks)")
    est = total / wps + boundary * (len(SCENES) - 1) + sum(breaks(sc["script"]) for sc in SCENES)
    print(f"total    {total:4d} words  ~{est/60:.1f} min incl. ~{boundary} s per clip boundary ({len(SCENES)} clips)")


def script():
    for sc in SCENES:
        print(f"[{sc['id']}] {sc.get('who', 'host')}, {'to camera' if sc['kind'] == 'cam' else 'over ' + sc.get('file', '')}\n")
        print("\n".join(plain(p) for p in re.split(r"\n\n|" + re.escape(BEAT), sc["script"]) if plain(p)))
        print("\n")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "help"
    if cmd == "export": export()
    elif cmd == "upload": upload()
    elif cmd == "request": request()
    elif cmd == "all": export(); upload(); request()
    elif cmd == "render": render(final="--final" in sys.argv)
    elif cmd == "words": words()
    elif cmd == "script": script()
    elif cmd == "mux": mux()
    elif cmd == "assemble": assemble()
    else: print(__doc__)
